import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./data/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#5f3f3a",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-primary": "#ff1e1e",
        "secondary-container": "#4a4949",
        "inverse-on-surface": "#2f3131",
        "primary-fixed": "#ffdad5",
        "secondary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-surface": "#e3e2e2",
        "on-secondary": "#313030",
        "on-error-container": "#ffdad6",
        "surface-container": "#1e2020",
        "on-surface-variant": "#e9bcb6",
        primary: "#ff1e1e",
        "on-tertiary-fixed": "#1c1b1b",
        "inverse-surface": "#e3e2e2",
        "on-secondary-fixed": "#1c1b1b",
        outline: "#b08782",
        "on-primary-container": "#ffffff",
        "on-primary": "#ffffff",
        "primary-container": "#ff1e1e",
        "tertiary-container": "#929090",
        "surface-container-lowest": "#0d0e0f",
        "tertiary-fixed": "#e5e2e1",
        background: "#121414",
        surface: "#121414",
        tertiary: "#c8c6c5",
        "on-secondary-container": "#bab8b7",
        "on-tertiary-container": "#2a2a2a",
        "surface-variant": "#343535",
        "on-primary-fixed": "#410001",
        "on-secondary-fixed-variant": "#474646",
        "on-primary-fixed-variant": "#930006",
        "error-container": "#93000a",
        secondary: "#c8c6c5",
        "surface-container-high": "#292a2a",
        "surface-container-highest": "#343535",
        "surface-bright": "#383939",
        "on-tertiary-fixed-variant": "#474746",
        "surface-container-low": "#1a1c1c",
        "surface-dim": "#121414",
        "surface-tint": "#ff1e1e",
        "on-background": "#e3e2e2",
        "on-error": "#690005",
        "primary-fixed-dim": "#ffb4aa",
        "on-tertiary": "#313030",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "max-width": "1440px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-anybody)", "sans-serif"],
        "headline-lg": ["var(--font-anybody)", "sans-serif"],
        "label-caps": ["var(--font-jetbrains)", "monospace"],
        "headline-xl": ["var(--font-anybody)", "sans-serif"],
        "body-md": ["var(--font-hanken)", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.1", fontWeight: "900" }],
        "headline-lg": ["48px", { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "900" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-xl": ["80px", { lineHeight: "0.9", letterSpacing: "-0.04em", fontWeight: "900" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      keyframes: {
        scroll: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-100%)" },
        },
        scan: {
          "0%": { top: "0%" },
          "100%": { top: "100%" },
        },
      },
      animation: {
        marquee: "scroll 30s linear infinite",
        "marquee-slow": "scroll 45s linear infinite",
        scan: "scan 4s linear infinite",
      },
      boxShadow: {
        premium: "0 0 30px rgba(255, 30, 30, 0.15)",
      },
    },
  },
  plugins: [],
};

export default config;
